export type HoundConfigRepo = {
  'url-pattern': {
    'base-url': string,
    anchor: string,
  };
  url: string;
  vcs: string;
  'vcs-config': {},
}

export type HoundConfig = {
  repos: {
    [key: string]: HoundConfigRepo;
  };
};

export type HoundFileMatch = {
    AutoGenerated: boolean;
    Filename: string;
    Matches: Array<{
        Line: string;
        Before: Array<string>;
        After: Array<string>;
        LineNumber: number;
    }>;
}

export type HoundRepoResult = {
    Matches: Array<HoundFileMatch>;
}

export type HoundRepoResults = {
    [key: string]: HoundRepoResult;
}

export type HoundSearchResult = {
  Results: HoundRepoResults;
};
